### ISSUE TITLE
Add tile version migrations from 1.0, 1.0.1 and 1.0.2 to 1.10.

### ISSUE THREAD

**Issue by spiegela** [thecodeteam/ecs-broker-tile#9]
For Ops Manager, version migrations are defined as Javascript files that convert previous tile properties to new ones.

An example of this can be found [here](https://github.com/thecodeteam/ecs-broker-tile/blob/master/migrations/v1/201710181816_noop.js).

**Comment by rogalv** [comment]
Already implemented.
